server:
  port: 8012
  servlet:
    context-path: /app-core2
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testMarket-core;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
#  flyway:
#    locations: classpath:/db/migration/test