server:
  port: 8080
  servlet:
    context-path: /app-core
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:springMarket-core;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false

  integrations:
    cart-service:
      url: http://localhost:8088/app-cart/
      connect-timeout: 5000
      read-timeout: 10000
      write-timeout: 5000

#  jwt:
#    secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
#    lifetime: 3600000

#  flyway:
#    locations=filesystem:db/migration: